version: '3.8'
services:
  backend:
    build: ./savannah-ai/backend
    ports:
      - "5000:5000"
    env_file:
      - ./savannah-ai/.env
    
    depends_on:
      - mongo

  frontend:
    build:
      context: ./savannah-ai
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    # Optionally, use build args or copy .env as shown above

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
